"""add_lifestyle_fields

Revision ID: 156ed407c44e
Revises: 76b65c439be2
Create Date: 2026-02-19 15:17:37.074289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156ed407c44e'
down_revision: Union[str, Sequence[str], None] = '76b65c439be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('diet_goal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('daily_sleep_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_water_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_water_goal')
        batch_op.drop_column('daily_sleep_goal')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('diet_goal')
        batch_op.drop_column('body_type')

    # ### end Alembic commands ###
