"""add_chatbot_context_fields

Revision ID: 5373d95b3c76
Revises: 156ed407c44e
Create Date: 2026-02-19 17:35:26.190301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5373d95b3c76'
down_revision: Union[str, Sequence[str], None] = '156ed407c44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injuries', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dietary_preferences', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dietary_preferences')
        batch_op.drop_column('injuries')

    # ### end Alembic commands ###
