"""add replay_data to workouts

Revision ID: 76b65c439be2
Revises: 648deda38ec9
Create Date: 2026-02-01 22:49:26.942961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b65c439be2'
down_revision: Union[str, Sequence[str], None] = '648deda38ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replay_data', sa.String(), nullable=True))
        batch_op.alter_column('exercise',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('exercise',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('replay_data')

    # ### end Alembic commands ###
